### ISSUE TITLE
Ability to auto popout windows when they are clicked

### ISSUE THREAD

**Issue by KShivum** [kakaroto/fvtt-module-popout#19]
Sorry, I'm not sure how to tag stuff correctly, but I have a feature request to have a setting that auto pops out windows when they are opened in foundry instead of opening it in the original browser window then waiting for it to pop out after clicking it

**Comment by kakaroto** [comment]
Hi,
Thanks for the suggestion, but after reflection I think this is a bad idea to implement it, because every time you popout a sheet, you're basically connection as a new user to the VTT, which means the entire world data gets downloaded again. Imagine a 50MB world and you're looking for some specific information and you end up opening dozens of journal entries causing nearly a GB of data to be transferred to you from the server. There's a reason why popping out a sheet is slow.

There is also no way to pop a sheet back into the main foundry window, so it makes more sense to pop it out rather than have it always opening in a popout and be locked in that state. Besides, the popout is a foundry window in its own right, and it doesn't differentiate much with the 'main' window. And what happens if you open a journal entry that has references to other entries, etc.. it can get complicated.

It saves you one click but potentially adds too much complexity and too many negatives if it were to be implemented.
